"""Regenerate examples/calibration/{gold,reviews}.yaml (seeded, synthetic data).

Five reviewers grade the same 24 gold items of code-explanation.yaml: asha and
dara are unbiased with some noise, chen scores clarity one point high, bruno
scores correctness one point low, and emeka is accurate for the first half and
drifts one point low on every criterion for the second half.

    uv run python scripts/gen_calibration_example.py
"""

from __future__ import annotations

import random
from datetime import UTC, datetime, timedelta
from pathlib import Path

from rubricops.loaders import load_rubric

ROOT = Path(__file__).resolve().parents[1]
RUBRIC = load_rubric(ROOT / "examples" / "rubrics" / "code-explanation.yaml")
START = datetime(2026, 9, 1, 9, 0, tzinfo=UTC)
N_ITEMS = 24
REVIEWERS = {
    "asha": {},
    "bruno": {"correctness": -1},
    "chen": {"clarity": 1},
    "dara": {},
    "emeka": {},
}


def _flow(scores: dict[str, int]) -> str:
    return "{" + ", ".join(f"{k}: {v}" for k, v in scores.items()) + "}"


def main() -> None:
    rng = random.Random(20260929)  # noqa: S311 - reproducible synthetic data
    scales = {c.id: c.scale for c in RUBRIC.criteria}
    gold = {
        f"gold-{i:02d}": {cid: rng.randint(s.low, s.high) for cid, s in scales.items()}
        for i in range(1, N_ITEMS + 1)
    }
    header = "# Generated by scripts/gen_calibration_example.py; synthetic, seeded.\n"
    lines = [header, f"rubric: {RUBRIC.id}\n", "items:\n"]
    lines += [f"  - {{id: {item}, scores: {_flow(s)}}}\n" for item, s in gold.items()]
    (ROOT / "examples" / "calibration" / "gold.yaml").write_text("".join(lines))

    out = [header, "reviews:\n"]
    for reviewer, offset in REVIEWERS.items():
        for i, (item, truth) in enumerate(gold.items()):
            drift = -1 if reviewer == "emeka" and i >= N_ITEMS // 2 else 0
            scores = {}
            for cid, value in truth.items():
                noise = rng.choice((-1, 1)) if rng.random() < 0.15 else 0
                raw = value + offset.get(cid, 0) + drift + noise
                scores[cid] = max(scales[cid].low, min(scales[cid].high, raw))
            at = (START + timedelta(hours=i)).strftime("%Y-%m-%dT%H:%M:%SZ")
            out.append(
                f"  - {{reviewer: {reviewer}, item: {item}, at: '{at}', scores: {_flow(scores)}}}\n"
            )
    (ROOT / "examples" / "calibration" / "reviews.yaml").write_text("".join(out))


if __name__ == "__main__":
    main()
